### ISSUE TITLE
Use independant RNGs to setup and query arroy

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/vector-store-relevancy-benchmark#1]
If we do that and seed the query rng with 13 (that we should define in a const), we are sure that Qdrant and Arroy will fetch the same vectors.

https://github.com/meilisearch/vector-store-relevancy-benchmark/blob/94f476b6cc60dfbdadc99e5ad4474c0511600ac6/src/arroy_bench.rs#L31-L37

**Comment by irevoire** [comment]
Fixed in https://github.com/meilisearch/vector-store-relevancy-benchmark/commit/ad53ce97ecb5c81c0ef9877539d56447d246153d
